# Jekyll configuration for GitHub Pages
title: "israel-economic-impact-database-2020-2024-key-indicators-main-factors-and-financ"
description: "This dataset provides a comprehensive overview of Israel's economic impact over the last five years (2020&ndash;2024), compiled from Perplexity AI aggregating data from TradingEconomics, World Bank, IMF, Bank of Israel, Jefferies, Wikipedia, Times of"
url: "https://juanmoisesd.github.io"
baseurl: "/israel-economic-impact-database-2020-2024-key-indicators-main-factors-and-financ"

author:
  name: "Juan Moisés de la Serna Tuya"
  orcid: "0000-0002-8401-8018"
  linkedin: "https://www.linkedin.com/in/juanmoisesdelaserna/"
  scopus: "26632846700"
  institution: "Universidad Internacional de La Rioja (UNIR)"
  email: "juanmoises.delaserna@unir.net"

# SEO
tagline: "Open Research Dataset"
lang: "en"

# Social
twitter:
  username: juanmoisesd
  card: summary

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build
theme: minima
include:
  - README.md
  - GLOSSARY.md
  - ABOUT_THE_AUTHOR.md
  - CITATION_GUIDE.md

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
